//
// Created by saleh on 8/22/21.
//

#ifndef DEEPPOINTV2FPGA_SRC_FPGA_XILINX_CLAYERWRAPPER_H_
#define DEEPPOINTV2FPGA_SRC_FPGA_XILINX_CLAYERWRAPPER_H_

class CLayerWrapper {

};

#endif //DEEPPOINTV2FPGA_SRC_FPGA_XILINX_CLAYERWRAPPER_H_
